#define P14D_INCLUDE_CAT(a, b) a##b
#define P14D_INCLUDE_PICK(name) P14D_INCLUDE_CAT(P14D_INCLUDE_VALUE_, name)
#define P14D_INCLUDE_VALUE_MODE 2
#define P14D_INCLUDE_ANY(...) (__VA_ARGS__)

#if P14D_INCLUDE_ANY(P14D_INCLUDE_PICK(MODE) == 2)
#define P14D_INCLUDE_SELECTED 1
#else
#define P14D_INCLUDE_SELECTED 0
#endif

#if P14D_INCLUDE_PICK(P14D_INCLUDE_MISSING_SUFFIX) == 1
#endif
