#if P14C_INCLUDE_CONFIG_EXPR == 5
#define P14C_INCLUDE_CHAIN 1
#else
#define P14C_INCLUDE_CHAIN 0
#endif

#define P14C_INCLUDE_SOURCE_OVERRIDE 7
#if P14C_INCLUDE_SOURCE_OVERRIDE == 7
#define P14C_INCLUDE_OVERRIDE_OK 1
#else
#define P14C_INCLUDE_OVERRIDE_OK 0
#endif

#if P14C_INCLUDE_MISSING_EXPR == 1
#endif

#if P14C_INCLUDE_CHAIN && P14C_INCLUDE_OVERRIDE_OK
#define P14C_INCLUDE_RESULT 1
#else
#define P14C_INCLUDE_RESULT 0
#endif
