#define P14I_FORWARD_ENUM 3

#undef P14I_OVERRIDE_ENUM
#define P14I_OVERRIDE_ENUM 5

#define P14I_CONFLICT_ENUM 2
#define P14I_CONFLICT_ENUM 4

#define P14I_UNDEF_ENUM 1
#undef P14I_UNDEF_ENUM

#define P14I_EXPR_ENUM (1 + 0)

#define P14I_FUNCTION_ENUM(x) x
